version: '3.8'
services:
  java-openjdk:
    build: .
    image: ragedunicorn/openjdk:${JAVA_TAG_VERSION}-jre-dev
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    labels:
      com.ragedunicorn.java-openjdk.environment: "dev"
      com.ragedunicorn.java-openjdk.description: "Java OpenJDK JRE environment"
