version: '3.6'
services:
  java-openjdk:
    build: .
    image: ragedunicorn/openjdk:1.0.1-jre-dev
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    labels:
      com.ragedunicorn.java-openjdk.environment: "dev"
      com.ragedunicorn.java-openjdk.description: "Java OpenJDK JRE environment"
