version: '3.6'
services:
  java-openjdk:
    build: .
    image: ragedunicorn/openjdk:${JAVA_TAG_VERSION}-jdk-stable
    labels:
      com.ragedunicorn.java-openjdk.environment: "prod"
      com.ragedunicorn.java-openjdk.description: "Java OpenJDK JDK environment"
