version: '3.6'
services:
  container-test-metadata:
    image: ragedunicorn/container-test:1.0.0-stable
    volumes:
        - ./test/:/test
        - /var/run/docker.sock:/var/run/docker.sock
    command: ["--image", "ragedunicorn/openjdk:1.0.2-jdk-stable", "--config", "/test/jdk_metadata_test.yml"]
    labels:
      com.ragedunicorn.container-test.environment: "test"
      com.ragedunicorn.container-test.description: "Google Container Structure Test"
  container-test-command:
    image: ragedunicorn/container-test:1.0.0-stable
    volumes:
        - ./test/:/test
        - /var/run/docker.sock:/var/run/docker.sock
    command: ["--image", "ragedunicorn/openjdk:1.0.2-jdk-stable", "--config", "/test/jdk_command_test.yml"]
    labels:
      com.ragedunicorn.container-test.environment: "test"
      com.ragedunicorn.container-test.description: "Google Container Structure Test"
  container-dev-test-metadata:
    image: ragedunicorn/container-test:1.0.0-stable
    volumes:
        - ./test/:/test
        - /var/run/docker.sock:/var/run/docker.sock
    command: ["--image", "ragedunicorn/openjdk:1.0.2-jdk-dev", "--config", "/test/jdk_metadata_test.yml"]
    labels:
      com.ragedunicorn.container-test.environment: "test"
      com.ragedunicorn.container-test.description: "Google Container Structure Test"
  container-dev-test-command:
    image: ragedunicorn/container-test:1.0.0-stable
    volumes:
        - ./test/:/test
        - /var/run/docker.sock:/var/run/docker.sock
    command: ["--image", "ragedunicorn/openjdk:1.0.2-jdk-dev", "--config", "/test/jdk_command_test.yml"]
    labels:
      com.ragedunicorn.container-test.environment: "test"
      com.ragedunicorn.container-test.description: "Google Container Structure Test"
